import type { Metadata } from "next";
import "./globals.css";
import { ConvexClientProvider } from "@/providers/convex-client-provider";
import { Toaster } from "sonner";
import ModalProvider from "@/providers/modal-provider";

export const metadata: Metadata = {
  title: "Renduit Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ConvexClientProvider>
          <Toaster></Toaster>
          <ModalProvider></ModalProvider>
          {children}
        </ConvexClientProvider>
      </body>
    </html>
  );
}
